const words = {
  "Bollywood Songs": [
    "Jalebi Bai",
    "Saki Saki",
    "Badtameez Dil",
    "Sheila Ki Jawani",
    "Kala Chashma",
    "Tauba Tauba",
    "Chittiyan Kalaiyaan",
    "Chammak Challo",
    "Mauja Hi Mauja",
    "Kajra Re",
    "Aankh Mare",
    "What Jhumka",
    "Sharara",
    "Tip Tip",
    "All Izz Well",
    "Pushpa",
    "Coca Cola",
    "Jhoome Jo Pathaan",
    "Garmi",
    "Chalo Ishq Ladayein",
    "Blue Eyes",
    "Baala",
    "Lungi Dance",
    "Lat Lag Gyi",
  ],
  "Things We Have At Home": [
    "Comb",
    "ToothPaste",
    "Spatula",
    "Suitcase",
    "Almirah",
    "Mirror",
    "Calendar",
    "Mop",
    "Clock",
    "Carpet",
    "Doormat",
    "Remote",
    "Belan/Rolling Pin",
    "CCTV",
    "Harpic",
    "Mortein",
    "Mosquito Coil",
    "Machardani",
    "Umbrella",
    "Vase",
    "Amplifier",
    "Pump/Motor/Summer",
    "Speakers",
    "Siblings",
    "Kundi",
  ],
  Foods: [
    "Fig(Anjeer)",
    "Sandwich",
    "Cereal",
    "Brownie",
    "Elaichi",
    "Pineapple",
    "Plum",
    "Avocado",
    "Bread",
    "Milkshake",
    "Pancakes",
    "Mushrooms",
    "Watermelon",
    "Almond",
    "Makhana",
    "Burger",
    "Okra",
    "Cupcake",
    "Tacos",
    "Doritos",
    "Kurkure",
    "KatHal/Jackfruit",
    "Pulao",
    "Egg",
    "Pasta",
    "Gulab Jamun",
  ],
  Games: [
    "Candy Crush",
    "Barbie",
    "Hot Wheels",
    "Connect",
    "Flow free",
    "Domino",
    "Tetris",
    "Talking Tom",
    "Crazy Taxi",
    "Pokemon",
    "Chess",
    "Subway Surfers",
    "Jenga",
    "Monopoly",
    "Plants vs Zombies",
    "Temple Run",
    "Among Us",
    "Purble Palace",
    "Flappy Bird",
    "PUBG",
    "Angry Bird",
    "Killzone",
    "Uncharted",
    "GTA",
    "Tekeen",
    "Minecraft",
    "Fruit Ninja",
    "Hill Climb Racing",
    "Where is my Water?",
  ],
  "Bollywood Movies": [
    "Ra One",
    "Chennai Express",
    "Andhadhun",
    "Chhichhore",
    "K3G",
    "DDLJ",
    "Jab We Met",
    "3 Idiots",
    "Taare Zameen Par",
    "PK",
    "Tubelight",
    "Stree",
    "Laila Majnu",
    "Pathaan",
    "Jawaan",
    "Lagaan",
    "Dream Girl",
    "Dhamaal",
    "Hera Pheri",
    "Kabir Singh",
    "Gangu Bai",
    "Golmal",
    "Holiday",
    "Pushpa",
    "Chillar Party",
    "Race",
    "Welcome",
    "Dear Zindagi",
    "Chup Chup Ke",
    "Fukrey",
    "12th Fail",
    "Hindi Medium",
    "English Winglish",
  ],
};
